
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 31 12:25:56 CST 2019
//----------------------------------------------------

package lexanalyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FinSentencia = 36;
  public static final int Into = 13;
  public static final int Between = 30;
  public static final int Clustered = 67;
  public static final int OpenRowset = 19;
  public static final int Where = 16;
  public static final int Punto = 44;
  public static final int Default = 22;
  public static final int Current = 89;
  public static final int Count = 54;
  public static final int Local = 107;
  public static final int Output = 93;
  public static final int Negativo = 4;
  public static final int Unique = 65;
  public static final int For = 109;
  public static final int Modify = 90;
  public static final int Star = 51;
  public static final int Fetch = 111;
  public static final int Procedure = 96;
  public static final int Add = 88;
  public static final int Max = 55;
  public static final int Cursor = 106;
  public static final int Int = 72;
  public static final int Returns = 98;
  public static final int Values = 20;
  public static final int Null = 23;
  public static final int Bit = 75;
  public static final int Create = 63;
  public static final int Global = 108;
  public static final int ERROR = 43;
  public static final int Varchar = 73;
  public static final int Update = 95;
  public static final int Insert = 14;
  public static final int Begin = 100;
  public static final int String = 40;
  public static final int Commit = 103;
  public static final int Transaction = 102;
  public static final int Set = 94;
  public static final int Collate = 81;
  public static final int Primary = 78;
  public static final int Desc = 71;
  public static final int End = 101;
  public static final int Function = 97;
  public static final int Some = 28;
  public static final int File = 83;
  public static final int Column = 87;
  public static final int Day = 57;
  public static final int Group = 86;
  public static final int Size = 84;
  public static final int ParentesisC = 7;
  public static final int ParentesisA = 2;
  public static final int Month = 59;
  public static final int Table = 49;
  public static final int In = 31;
  public static final int Open = 110;
  public static final int Identity = 79;
  public static final int And = 24;
  public static final int Or = 26;
  public static final int Drop = 17;
  public static final int Database = 48;
  public static final int On = 50;
  public static final int Truncate = 66;
  public static final int Key = 80;
  public static final int If = 32;
  public static final int User = 64;
  public static final int Comentario_Incompleto = 10;
  public static final int EOF = 0;
  public static final int Distinct = 35;
  public static final int By = 61;
  public static final int Comma = 5;
  public static final int Positivo = 3;
  public static final int From = 12;
  public static final int Inner = 52;
  public static final int Constraint = 77;
  public static final int Declare = 105;
  public static final int Login = 45;
  public static final int DefaultValues = 21;
  public static final int Object = 69;
  public static final int error = 1;
  public static final int Top = 15;
  public static final int Name = 82;
  public static final int Asc = 70;
  public static final int Next = 112;
  public static final int Float = 74;
  public static final int Like = 29;
  public static final int PuntoComma = 6;
  public static final int Year = 58;
  public static final int Join = 53;
  public static final int Sum = 34;
  public static final int At = 8;
  public static final int As = 62;
  public static final int NonClustered = 68;
  public static final int Identificador = 37;
  public static final int Select = 11;
  public static final int All = 27;
  public static final int SavePoint = 99;
  public static final int Include = 76;
  public static final int Entero = 39;
  public static final int Rollback = 104;
  public static final int Comentario = 9;
  public static final int Not = 25;
  public static final int Exists = 33;
  public static final int View = 47;
  public static final int OpenQuery = 18;
  public static final int Delete = 91;
  public static final int Alter = 85;
  public static final int Percent = 92;
  public static final int Index = 46;
  public static final int Min = 56;
  public static final int Order = 60;
  public static final int Operador = 42;
  public static final int Decimal = 38;
  public static final int Boolean = 41;
}

