
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 28 22:21:52 CST 2019
//----------------------------------------------------

package lexanalyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FinSentencia = 36;
  public static final int Into = 13;
  public static final int Between = 30;
  public static final int Clustered = 67;
  public static final int OpenRowset = 19;
  public static final int Where = 16;
  public static final int Punto = 44;
  public static final int Default = 22;
  public static final int Count = 54;
  public static final int Negativo = 4;
  public static final int Unique = 65;
  public static final int Star = 51;
  public static final int Max = 55;
  public static final int Values = 20;
  public static final int Null = 23;
  public static final int Create = 63;
  public static final int ERROR = 43;
  public static final int Insert = 14;
  public static final int String = 40;
  public static final int Desc = 71;
  public static final int Some = 28;
  public static final int Day = 57;
  public static final int ParentesisC = 7;
  public static final int ParentesisA = 2;
  public static final int Month = 59;
  public static final int Table = 49;
  public static final int In = 31;
  public static final int And = 24;
  public static final int Or = 26;
  public static final int Drop = 17;
  public static final int Database = 48;
  public static final int On = 50;
  public static final int Truncate = 66;
  public static final int If = 32;
  public static final int User = 64;
  public static final int Comentario_Incompleto = 10;
  public static final int EOF = 0;
  public static final int Distinct = 35;
  public static final int By = 61;
  public static final int Comma = 5;
  public static final int Positivo = 3;
  public static final int From = 12;
  public static final int Inner = 52;
  public static final int Login = 45;
  public static final int DefaultValues = 21;
  public static final int Object = 69;
  public static final int error = 1;
  public static final int Top = 15;
  public static final int Asc = 70;
  public static final int Like = 29;
  public static final int PuntoComma = 6;
  public static final int Year = 58;
  public static final int Join = 53;
  public static final int Sum = 34;
  public static final int At = 8;
  public static final int As = 62;
  public static final int NonClustered = 68;
  public static final int Identificador = 37;
  public static final int Select = 11;
  public static final int All = 27;
  public static final int Include = 72;
  public static final int Entero = 39;
  public static final int Comentario = 9;
  public static final int Not = 25;
  public static final int Exists = 33;
  public static final int View = 47;
  public static final int OpenQuery = 18;
  public static final int Index = 46;
  public static final int Min = 56;
  public static final int Order = 60;
  public static final int Operador = 42;
  public static final int Decimal = 38;
  public static final int Boolean = 41;
}

