
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 27 22:38:15 CST 2019
//----------------------------------------------------

package lexanalyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int In = 30;
  public static final int Or = 25;
  public static final int Comma = 5;
  public static final int Entero = 37;
  public static final int Distinct = 33;
  public static final int Like = 28;
  public static final int Sum = 32;
  public static final int Null = 22;
  public static final int All = 26;
  public static final int OpenQuery = 17;
  public static final int From = 12;
  public static final int Default = 21;
  public static final int Operador = 40;
  public static final int Into = 13;
  public static final int Comentario = 9;
  public static final int Select = 11;
  public static final int Punto = 42;
  public static final int Values = 19;
  public static final int Comentario_Incompleto = 10;
  public static final int Exists = 31;
  public static final int EOF = 0;
  public static final int Not = 24;
  public static final int And = 23;
  public static final int error = 1;
  public static final int At = 8;
  public static final int Between = 29;
  public static final int Some = 27;
  public static final int FinSentencia = 34;
  public static final int OpenRowset = 18;
  public static final int ERROR = 41;
  public static final int PuntoComma = 6;
  public static final int Insert = 14;
  public static final int String = 38;
  public static final int Negativo = 4;
  public static final int Identificador = 35;
  public static final int DefaultValues = 20;
  public static final int Top = 15;
  public static final int ParentesisC = 7;
  public static final int Boolean = 39;
  public static final int Decimal = 36;
  public static final int ParentesisA = 2;
  public static final int Where = 16;
  public static final int Positivo = 3;
}

